// src/components/screens/SearchScreen.jsx
"use client";

import { Search } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { HOME_AIRPORT_COUNTRY } from "../../config/homeAirportDirectory.js";
import { airportDirectoryClient } from "../../services/airportDirectory.js";
import { airportSubtitle } from "../../utils/airport.js";
import {
  THEME_DARK,
  THEME_LIGHT,
  THEME_SYSTEM,
  applyThemePreference,
  initThemePreference,
  nextTheme,
  writeStoredTheme,
} from "../../utils/theme.js";
import ThemeModeIcon from "../ui/icons/ThemeModeIcon";

const featuredAirports = [
  {
    icao: "KBOS",
    iata: "BOS",
    name: "Boston Logan International Airport",
    city: "Boston",
    country: "US",
    lat: 42.3656,
    lon: -71.0096,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "KLAX",
    iata: "LAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    country: "US",
    lat: 33.9425,
    lon: -118.4081,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "KJFK",
    iata: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    country: "US",
    lat: 40.6413,
    lon: -73.7781,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "KORD",
    iata: "ORD",
    name: "Chicago O'Hare International Airport",
    city: "Chicago",
    country: "US",
    lat: 41.9742,
    lon: -87.9073,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "KSFO",
    iata: "SFO",
    name: "San Francisco International Airport",
    city: "San Francisco",
    country: "US",
    lat: 37.6213,
    lon: -122.379,
    type: "large_airport",
    type_label: "Large Airport",
  },
  {
    icao: "KSEA",
    iata: "SEA",
    name: "Seattle-Tacoma International Airport",
    city: "Seattle",
    country: "US",
    lat: 47.4502,
    lon: -122.3088,
    type: "large_airport",
    type_label: "Large Airport",
  },
];

export default function SearchScreen({ onOpenAirport }) {
  const [q, setQ] = useState("");
  const [focused, setFocused] = useState(false);
  const [results, setResults] = useState([]);
  const [searchLoading, setSearchLoading] = useState(false);
  const [searchError, setSearchError] = useState(null);
  const [themePreference, setThemePreference] = useState(THEME_SYSTEM);
  const activeRequestId = useRef(0);
  const mediaQueryList = useRef(null);

  useEffect(() => {
    mediaQueryList.current = window.matchMedia("(prefers-color-scheme: dark)");
    setThemePreference(
      initThemePreference({ mediaQueryList: mediaQueryList.current }).preference,
    );
    const listener = () => {
      if (themePreference === THEME_SYSTEM) {
        applyThemePreference({
          theme: THEME_SYSTEM,
          mediaQueryList: mediaQueryList.current,
        });
      }
    };
    mediaQueryList.current.addEventListener("change", listener);
    return () => mediaQueryList.current?.removeEventListener("change", listener);
  }, [themePreference]);

  const themeTitle = useMemo(() => {
    if (themePreference === THEME_LIGHT) return "Theme: Light (click to switch)";
    if (themePreference === THEME_DARK) return "Theme: Dark (click to switch)";
    return "Theme: System (click to switch)";
  }, [themePreference]);

  const cycleTheme = () => {
    const next = nextTheme(themePreference);
    setThemePreference(next);
    writeStoredTheme(next);
    applyThemePreference({ theme: next, mediaQueryList: mediaQueryList.current });
  };

  const searchRows = useMemo(() => {
    const query = q.trim().toUpperCase();
    if (!query) return [];
    const matchesFeatured = featuredAirports.filter((airport) =>
      [airport.icao, airport.iata, airport.name, airport.city, airport.country]
        .join(" ")
        .toUpperCase()
        .includes(query),
    );
    const seen = new Set();
    return [...matchesFeatured, ...results].filter((airport) => {
      const key = String(airport.icao || airport.code || airport.name || "")
        .trim()
        .toUpperCase();
      if (!key || seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  }, [q, results]);

  const resultCountLabel = searchLoading
    ? "loading"
    : `${searchRows.length} result${searchRows.length === 1 ? "" : "s"}`;

  useEffect(() => {
    const timer = setTimeout(
      async () => {
        const trimmed = q.trim();
        const requestId = ++activeRequestId.current;
        if (!trimmed) {
          setResults([]);
          setSearchLoading(false);
          setSearchError(null);
          return;
        }
        setSearchLoading(true);
        setSearchError(null);
        try {
          const payload = await airportDirectoryClient.loadAirports({
            query: trimmed,
            country: HOME_AIRPORT_COUNTRY,
            kind: "all",
            limit: 12,
          });
          if (requestId !== activeRequestId.current) return;
          setResults(payload.airports || []);
        } catch (err) {
          if (requestId !== activeRequestId.current) return;
          console.error("Airport search failed", err);
          setResults([]);
          setSearchError(err?.message || "Airport directory is unavailable right now");
        } finally {
          if (requestId === activeRequestId.current) setSearchLoading(false);
        }
      },
      q.trim() ? 220 : 0,
    );
    return () => clearTimeout(timer);
  }, [q]);

  const openAirport = (airport) => {
    onOpenAirport({
      code: airport.icao || airport.code,
      icao: airport.icao || airport.code,
      iata: airport.iata || airport.code,
      name: airport.name || airport.code,
      city: airport.city || "",
      country: airport.country || "",
      lat: airport.lat ?? null,
      lon: airport.lon ?? null,
      type: airport.type || "",
      type_label: airport.type_label || "",
    });
  };

  const doSearch = (event) => {
    event.preventDefault();
    const normalized = q.trim().toUpperCase();
    if (!normalized) return;
    const exact = [...searchRows, ...featuredAirports].find((airport) => {
      const icao = String(airport.icao || "").toUpperCase();
      const iata = String(airport.iata || "").toUpperCase();
      const code = String(airport.code || "").toUpperCase();
      return normalized === icao || normalized === iata || normalized === code;
    });
    openAirport(exact || searchRows[0]);
  };

  return (
    <div className="search-screen min-h-screen text-atc-text">
      <main className="grid min-h-screen place-items-start px-5 py-6 sm:place-items-center sm:p-10 lg:p-14">
        <section className="w-full max-w-[860px]">
          <div className="mb-4 flex items-center justify-between gap-2.5 font-mono text-[11px] uppercase tracking-[1.4px] text-atc-dim">
            <div className="flex items-center gap-2.5">
              <span className="text-atc-text">ADSBao</span>
              <span className="text-atc-orange">/</span>
              <span>Airport search</span>
            </div>
            <button
              type="button"
              className="theme-chip inline-flex h-8 items-center gap-1.5 rounded-full px-3 text-[12px] tracking-[0.2px] text-atc-dim transition hover:border-atc-orange/45 hover:text-atc-text"
              title={themeTitle}
              onClick={cycleTheme}
            >
              <ThemeModeIcon className="h-3.5 w-3.5" theme={themePreference} />
              <span>{themePreference}</span>
            </button>
          </div>

          <form
            onSubmit={doSearch}
            className={`search-input input flex h-auto w-full items-center gap-3 px-4 py-4 text-atc-text transition-[border-color,box-shadow] duration-150 sm:gap-3.5 sm:px-5 sm:py-5 ${
              focused
                ? "border-atc-orange/70 shadow-[0_30px_100px_rgba(0,0,0,0.42),0_0_0_1px_rgba(255,90,31,0.18)_inset]"
                : ""
            }`}
          >
            <Search className="h-5 w-5 shrink-0 text-atc-orange" />
            <input
              value={q}
              autoFocus
              onChange={(event) => setQ(event.target.value)}
              onFocus={() => setFocused(true)}
              onBlur={() => setFocused(false)}
              className="min-w-0 flex-1 border-0 bg-transparent p-0 text-2xl font-extrabold tracking-normal text-atc-text outline-none placeholder:text-atc-dim sm:text-3xl"
              placeholder="Search by ICAO, IATA, city, or airport name"
            />
            <kbd className="search-kbd kbd hidden shrink-0 font-mono text-[10px] uppercase tracking-[1px] text-atc-dim sm:inline-flex">
              {searchLoading ? "..." : "enter"}
            </kbd>
          </form>

          {q.trim() ? (
            <SearchResults
              q={q}
              rows={searchRows}
              loading={searchLoading}
              error={searchError}
              countLabel={resultCountLabel}
              onOpen={openAirport}
            />
          ) : (
            <FeaturedAirports onOpen={openAirport} />
          )}
        </section>
      </main>
    </div>
  );
}

function SearchResults({ q, rows, loading, error, countLabel, onOpen }) {
  return (
    <div className="mt-5">
      <div className="flex items-center justify-between border-b border-atc-line pb-2.5 font-mono text-[10px] uppercase tracking-[1.5px] text-atc-dim">
        <span>Search results</span>
        <span>{countLabel}</span>
      </div>

      {loading && !rows.length ? (
        <div className="py-7 text-center font-mono text-xs tracking-[0.6px] text-atc-dim">
          Searching airports...
        </div>
      ) : error ? (
        <div className="py-7 text-center font-mono text-xs tracking-[0.6px] text-atc-dim">
          {error}
        </div>
      ) : !rows.length ? (
        <div className="py-7 text-center font-mono text-xs tracking-[0.6px] text-atc-dim">
          No airport matched &quot;{q.trim()}&quot;.
        </div>
      ) : (
        <div className="mt-2.5 grid gap-2">
          {rows.map((airport) => (
            <AirportRow key={airport.icao || airport.code || airport.name} airport={airport} onOpen={onOpen} />
          ))}
        </div>
      )}
    </div>
  );
}

function FeaturedAirports({ onOpen }) {
  return (
    <div className="mt-5">
      <div className="flex items-center justify-between border-b border-atc-line pb-2.5 font-mono text-[10px] uppercase tracking-[1.5px] text-atc-dim">
        <span>Featured airports</span>
        <span>{featuredAirports.length}</span>
      </div>

      <div className="mt-2.5 grid gap-2">
        {featuredAirports.map((airport, index) => (
          <AirportRow
            key={airport.icao}
            airport={airport}
            onOpen={onOpen}
            featured={index === 0}
          />
        ))}
      </div>
    </div>
  );
}

function AirportRow({ airport, onOpen, featured = false }) {
  return (
    <button
      type="button"
      className={`search-row btn grid h-auto min-h-0 w-full grid-cols-[62px_minmax(0,1fr)] items-center justify-start gap-4 px-4 py-3.5 text-left font-sans normal-case text-atc-text hover:-translate-y-px hover:border-atc-orange/40 sm:grid-cols-[86px_minmax(0,1fr)_auto] ${
        featured ? "search-row--featured" : ""
      }`}
      onClick={() => onOpen(airport)}
    >
      <span className="font-display text-[32px] italic leading-[0.8] text-atc-orange sm:text-[38px]">
        {airport.iata || airport.icao || airport.code}
      </span>
      <span className="min-w-0">
        <strong className="block truncate text-[17px] font-extrabold tracking-normal text-atc-text">
          {airport.name}
        </strong>
        <small className="mt-0.5 block truncate text-[13px] text-atc-dim">
          {featured
            ? `${airport.city} / ${airport.country}`
            : airportSubtitle(airport)}
        </small>
      </span>
      <span className="badge hidden border-0 bg-transparent font-mono text-[11px] uppercase tracking-[1.2px] text-atc-dim sm:inline-flex">
        {airport.icao || airport.code || "-"}
      </span>
    </button>
  );
}

// src/components/screens/SearchScreen.vue
<template>
  <div class="search-screen min-h-screen text-atc-text">
    <main class="grid min-h-screen place-items-start px-5 py-6 sm:place-items-center sm:p-10 lg:p-14">
      <section class="w-full max-w-[860px]">
        <div class="mb-4 flex items-center justify-between gap-2.5 font-mono text-[11px] uppercase tracking-[1.4px] text-atc-dim">
          <div class="flex items-center gap-2.5">
            <span class="text-atc-text">ADSBao</span>
            <span class="text-atc-orange">/</span>
            <span>Airport search</span>
          </div>
          <button
            type="button"
            class="theme-chip inline-flex h-8 items-center gap-1.5 rounded-full px-3 text-[12px] tracking-[0.2px] text-atc-dim transition hover:border-atc-orange/45 hover:text-atc-text"
            :title="themeTitle"
            @click="cycleTheme"
          >
            <ThemeModeIcon class="h-3.5 w-3.5" :theme="themePreference" />
            <span>{{ themePreference }}</span>
          </button>
        </div>

        <label
          class="search-input input flex h-auto w-full items-center gap-3 px-4 py-4 text-atc-text transition-[border-color,box-shadow] duration-150 sm:gap-3.5 sm:px-5 sm:py-5"
          :class="{ 'border-atc-orange/70 shadow-[0_30px_100px_rgba(0,0,0,0.42),0_0_0_1px_rgba(255,90,31,0.18)_inset]': focused }"
        >
          <svg class="shrink-0 text-atc-orange" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="11" cy="11" r="8" />
            <line x1="21" y1="21" x2="16.65" y2="16.65" />
          </svg>
          <input
            v-model="q"
            autofocus
            @focus="focused = true"
            @blur="focused = false"
            @keydown.enter="doSearch"
            class="min-w-0 flex-1 border-0 bg-transparent p-0 text-2xl font-extrabold tracking-normal text-atc-text outline-none placeholder:text-atc-dim sm:text-3xl"
            placeholder="Search by ICAO, IATA, city, or airport name"
          />
          <kbd class="search-kbd kbd hidden shrink-0 font-mono text-[10px] uppercase tracking-[1px] text-atc-dim sm:inline-flex">
            {{ searchLoading ? '...' : 'enter' }}
          </kbd>
        </label>

        <div v-if="q.trim()" class="mt-5">
          <div class="flex items-center justify-between border-b border-atc-line pb-2.5 font-mono text-[10px] uppercase tracking-[1.5px] text-atc-dim">
            <span>Search results</span>
            <span>{{ resultCountLabel }}</span>
          </div>

          <div v-if="searchLoading && !searchRows.length" class="py-7 text-center font-mono text-xs tracking-[0.6px] text-atc-dim">Searching airports...</div>
          <div v-else-if="searchError" class="py-7 text-center font-mono text-xs tracking-[0.6px] text-atc-dim">{{ searchError }}</div>
          <div v-else-if="!searchRows.length" class="py-7 text-center font-mono text-xs tracking-[0.6px] text-atc-dim">No airport matched "{{ q.trim() }}".</div>
          <div v-else class="mt-2.5 grid gap-2">
            <button
              v-for="airport in searchRows"
              :key="airport.icao || airport.code || airport.name"
              class="search-row btn grid h-auto min-h-0 w-full grid-cols-[62px_minmax(0,1fr)] items-center justify-start gap-4 px-4 py-3.5 text-left font-sans normal-case text-atc-text hover:-translate-y-px hover:border-atc-orange/40 sm:grid-cols-[86px_minmax(0,1fr)_auto]"
              @click="openAirport(airport)"
            >
              <span class="font-display text-[32px] italic leading-[0.8] text-atc-orange sm:text-[38px]">{{ airport.iata || airport.icao || airport.code }}</span>
              <span class="min-w-0">
                <strong class="block truncate text-[17px] font-extrabold tracking-normal text-atc-text">{{ airport.name }}</strong>
                <small class="mt-0.5 block truncate text-[13px] text-atc-dim">{{ airportSubtitle(airport) }}</small>
              </span>
              <span class="badge hidden border-0 bg-transparent font-mono text-[11px] uppercase tracking-[1.2px] text-atc-dim sm:inline-flex">{{ airport.icao || airport.code || '—' }}</span>
            </button>
          </div>
        </div>

        <div v-else class="mt-5">
          <div class="flex items-center justify-between border-b border-atc-line pb-2.5 font-mono text-[10px] uppercase tracking-[1.5px] text-atc-dim">
            <span>Featured airports</span>
            <span>{{ featuredAirports.length }}</span>
          </div>

          <div class="mt-2.5 grid gap-2">
            <button
              v-for="airport in featuredAirports"
              :key="airport.icao"
              class="search-row search-row--featured btn grid h-auto min-h-0 w-full grid-cols-[62px_minmax(0,1fr)] items-center justify-start gap-4 px-4 py-3.5 text-left font-sans normal-case text-atc-text hover:-translate-y-px hover:border-atc-orange/40 sm:grid-cols-[86px_minmax(0,1fr)_auto]"
              @click="openAirport(airport)"
            >
              <span class="font-display text-[32px] italic leading-[0.8] text-atc-orange sm:text-[38px]">{{ airport.iata }}</span>
              <span class="min-w-0">
                <strong class="block truncate text-[17px] font-extrabold tracking-normal text-atc-text">{{ airport.name }}</strong>
                <small class="mt-0.5 block truncate text-[13px] text-atc-dim">{{ airport.city }} · {{ airport.country }}</small>
              </span>
              <span class="badge hidden border-0 bg-transparent font-mono text-[11px] uppercase tracking-[1.2px] text-atc-dim sm:inline-flex">{{ airport.icao }}</span>
            </button>
          </div>
        </div>
      </section>
    </main>
  </div>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, onUnmounted, ref, watch } from 'vue'
import { airportDirectoryClient } from '../../services/airportDirectory.js'
import { HOME_AIRPORT_COUNTRY } from '../../config/homeAirportDirectory.js'
import { airportSubtitle } from '../../utils/airport.js'
import ThemeModeIcon from '../ui/icons/ThemeModeIcon.vue'
import {
  THEME_DARK,
  THEME_LIGHT,
  THEME_SYSTEM,
  applyThemePreference,
  initThemePreference,
  nextTheme,
  writeStoredTheme,
} from '../../utils/theme.js'

const emit = defineEmits(['open-airport'])

const q = ref('')
const focused = ref(false)
const results = ref([])
const searchLoading = ref(false)
const searchError = ref(null)

const featuredAirports = [
  {
    icao: 'KBOS',
    iata: 'BOS',
    name: 'Boston Logan International Airport',
    city: 'Boston',
    country: 'US',
    lat: 42.3656,
    lon: -71.0096,
    type: 'large_airport',
    type_label: 'Large Airport',
  },
  {
    icao: 'KLAX',
    iata: 'LAX',
    name: 'Los Angeles International Airport',
    city: 'Los Angeles',
    country: 'US',
    lat: 33.9425,
    lon: -118.4081,
    type: 'large_airport',
    type_label: 'Large Airport',
  },
  {
    icao: 'KJFK',
    iata: 'JFK',
    name: 'John F. Kennedy International Airport',
    city: 'New York',
    country: 'US',
    lat: 40.6413,
    lon: -73.7781,
    type: 'large_airport',
    type_label: 'Large Airport',
  },
  {
    icao: 'KORD',
    iata: 'ORD',
    name: "Chicago O'Hare International Airport",
    city: 'Chicago',
    country: 'US',
    lat: 41.9742,
    lon: -87.9073,
    type: 'large_airport',
    type_label: 'Large Airport',
  },
  {
    icao: 'KSFO',
    iata: 'SFO',
    name: 'San Francisco International Airport',
    city: 'San Francisco',
    country: 'US',
    lat: 37.6213,
    lon: -122.379,
    type: 'large_airport',
    type_label: 'Large Airport',
  },
  {
    icao: 'KSEA',
    iata: 'SEA',
    name: 'Seattle-Tacoma International Airport',
    city: 'Seattle',
    country: 'US',
    lat: 47.4502,
    lon: -122.3088,
    type: 'large_airport',
    type_label: 'Large Airport',
  },
]

let searchTimer = null
let activeRequestId = 0
const themePreference = ref(THEME_SYSTEM)
let mediaQueryList = null
let mediaQueryListener = null

const themeTitle = computed(() => {
  if (themePreference.value === THEME_LIGHT) return 'Theme: Light (click to switch)'
  if (themePreference.value === THEME_DARK) return 'Theme: Dark (click to switch)'
  return 'Theme: System (click to switch)'
})

const cycleTheme = () => {
  const next = nextTheme(themePreference.value)
  themePreference.value = next
  writeStoredTheme(next)
  applyThemePreference({ theme: next, mediaQueryList })
}

const searchRows = computed(() => {
  const query = q.value.trim().toUpperCase()
  if (!query) return []

  const matchesFeatured = featuredAirports.filter((airport) => {
    const haystack = [
      airport.icao,
      airport.iata,
      airport.name,
      airport.city,
      airport.country,
    ].join(' ').toUpperCase()
    return haystack.includes(query)
  })

  const seen = new Set()
  return [...matchesFeatured, ...results.value].filter((airport) => {
    const key = String(airport.icao || airport.code || airport.name || '').toUpperCase()
    if (!key || seen.has(key)) return false
    seen.add(key)
    return true
  })
})

const resultCountLabel = computed(() => {
  if (searchLoading.value) return 'loading'
  return `${searchRows.value.length} result${searchRows.value.length === 1 ? '' : 's'}`
})

const loadAirports = async (query) => {
  const trimmed = String(query || '').trim()
  const requestId = ++activeRequestId

  if (!trimmed) {
    results.value = []
    searchLoading.value = false
    searchError.value = null
    return
  }

  searchLoading.value = true
  searchError.value = null
  try {
    const payload = await airportDirectoryClient.loadAirports({
      query: trimmed,
      country: HOME_AIRPORT_COUNTRY,
      kind: 'all',
      limit: 12,
    })
    if (requestId !== activeRequestId) return
    results.value = payload.airports || []
  } catch (err) {
    if (requestId !== activeRequestId) return
    console.error('Airport search failed', err)
    results.value = []
    searchError.value = err?.message || 'Airport directory is unavailable right now'
  } finally {
    if (requestId === activeRequestId) {
      searchLoading.value = false
    }
  }
}

const doSearch = () => {
  const normalized = q.value.trim().toUpperCase()
  if (!normalized) return

  const exact = [...searchRows.value, ...featuredAirports].find((airport) => {
    const icao = String(airport.icao || '').toUpperCase()
    const iata = String(airport.iata || '').toUpperCase()
    const code = String(airport.code || '').toUpperCase()
    return normalized === icao || normalized === iata || normalized === code
  })

  if (exact) {
    openAirport(exact)
    return
  }

  if (searchRows.value[0]) {
    openAirport(searchRows.value[0])
  }
}

const openAirport = (airport) => {
  emit('open-airport', {
    code: airport.icao || airport.code,
    icao: airport.icao || airport.code,
    iata: airport.iata || airport.code,
    name: airport.name || airport.code,
    city: airport.city || '',
    country: airport.country || '',
    lat: airport.lat ?? null,
    lon: airport.lon ?? null,
    type: airport.type || '',
    type_label: airport.type_label || '',
  })
}

watch(q, (value) => {
  clearTimeout(searchTimer)
  searchTimer = setTimeout(() => {
    loadAirports(value)
  }, value.trim() ? 220 : 0)
})

onMounted(() => {
  mediaQueryList = window.matchMedia('(prefers-color-scheme: dark)')
  themePreference.value = initThemePreference({ mediaQueryList }).preference
  mediaQueryListener = () => {
    if (themePreference.value === THEME_SYSTEM) {
      applyThemePreference({ theme: THEME_SYSTEM, mediaQueryList })
    }
  }
  mediaQueryList.addEventListener('change', mediaQueryListener)
})

onBeforeUnmount(() => {
  if (mediaQueryList && mediaQueryListener) {
    mediaQueryList.removeEventListener('change', mediaQueryListener)
  }
})

onUnmounted(() => {
  clearTimeout(searchTimer)
})
</script>

<style scoped>
.search-screen {
  background:
    radial-gradient(
      circle at 22% 12%,
      color-mix(in oklab, var(--atc-orange) 22%, transparent),
      transparent 32%
    ),
    radial-gradient(
      circle at 78% 80%,
      color-mix(in oklab, var(--atc-line) 50%, transparent),
      transparent 34%
    ),
    linear-gradient(
      135deg,
      color-mix(in oklab, var(--atc-orange) 8%, transparent),
      transparent 38%
    ),
    var(--atc-bg);
}

.theme-chip {
  background: color-mix(in oklab, var(--atc-card) 72%, transparent);
  border: 1px solid color-mix(in oklab, var(--atc-line-strong) 82%, transparent);
  font-family: var(--font-sans);
}

.search-input {
  background: linear-gradient(
    145deg,
    color-mix(in oklab, var(--atc-card) 84%, transparent),
    color-mix(in oklab, var(--atc-elev) 88%, transparent)
  );
  border: 1px solid color-mix(in oklab, var(--atc-line-strong) 82%, transparent);
  border-radius: 26px;
  box-shadow:
    0 26px 90px color-mix(in oklab, var(--atc-bg) 62%, transparent),
    inset 0 1px 0 color-mix(in oklab, var(--atc-line-strong) 58%, transparent);
}

.search-kbd {
  background: transparent;
  border: 1px solid var(--atc-line-strong);
}

.search-row {
  background: color-mix(in oklab, var(--atc-card) 62%, transparent);
  border: 1px solid color-mix(in oklab, var(--atc-line-strong) 78%, transparent);
  border-radius: 18px;
}

.search-row:hover {
  background: color-mix(in oklab, var(--atc-card) 76%, transparent);
}

.search-row--featured:first-child {
  background: linear-gradient(
    100deg,
    color-mix(in oklab, var(--atc-orange) 16%, transparent),
    color-mix(in oklab, var(--atc-card) 72%, transparent)
  );
}
</style>
